workflows:
  my-workflow:
    publishing:
      app_store_connect:
        api_key: $APPLE_PRIVATE_KEY
        key_id: $KEY_ID
        issuer_id: $ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
