name: hearooz
description: A new Flutter project.

publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  audio_service: ^0.18.0-beta.0
  audio_video_progress_bar: ^0.10.0
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  get_it: ^7.1.2
  http: ^0.13.4
  just_audio: ^0.9.5
  lottie: ^1.4.1
  miniplayer: ^1.0.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  toast: ^0.3.0
  url_launcher: ^6.1.2
  wave: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
